#theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
    "Reddit":
      - "https://www.reddit.com/r/minibolt/"
    "Contribute! Source on GitHub":
      - "https://github.com/twofaktor/minibolt"
    
color_scheme: minibolt-dark.scss

# defaults
defaults:
  - scope:
      path: ""
    values:
      image: https://twofaktor.github.io/minibolt/images/minibolt-home-screen-og.png

# jekyll-seo-tag
twitter:
  card: summary_large_image
  username: twofaktor

title: MiniBolt
tagline: "Bitcoin & Lightning full node on a personal computer"
description: "Build your own “DIY” Bitcoin & Lightning full node on a personal computer. No need to trust anyone else."
type: website

# enable theme for local usage
#theme: "just-the-docs"

exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - README.md
